version: '3'

services:
  app:
    container_name: selfpod
    build: .
    ports:
      - "6000:5000"
    environment:
      - A_CAST_HOOK_TOKEN=token
      - APP_PORT=5000
      - GOOGLE_REDIRECT_URL=http://localhost:6000/
    volumes:
      - ./for_docker_mount/:/application/tmp_files/
      - ./files/:/application/files/
      - ./client_secret.json:/client_secret.json
      - ./selfpod.db:/selfpod.db
      - ./selfpod-logs.log:/selfpod-logs.log
