### Call a cast hook
POST {{url}}/acast?token={{token}}
Content-Type: application/json

{
  "event": "episodePublished",
  "id": "655a21197d946a0012ec4e5c",
  "title": "My new episode 11",
  "status": "published",
  "publishDate": "2020-01-13T21:57:57.768Z",
  "coverUrl": "https://kanapaimage.ams3.digitaloceanspaces.com/cocktails/20/origin/20.jpg",
  "audioUrl": "https://kanapaimage.ams3.digitaloceanspaces.com/tmp/5m.wav"
}


### Call login to google
POST {{url}}/login?token={{token}}

###
GET http://localhost:6000/auth/google/callback


###
POST http://localhost:6000/add
Content-Type: application/json

{
  "event": "episodePublished",
  "id": "655a21197d946a0012ec4e5c",
  "title": "My new episode 11",
  "status": "published",
  "publishDate": "2020-01-13T21:57:57.768Z",
  "coverUrl": "https://kanapaimage.ams3.digitaloceanspaces.com/cocktails/20/origin/20.jpg",
  "audioUrl": "https://kanapaimage.ams3.digitaloceanspaces.com/tmp/5m.wav"
}
