name: Build Image Cross Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu:22.04
    steps:
      - uses: http://gitea.com/actions/checkout@v2
      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v1

      - name: Docker meta
        id: meta
        uses: https://github.com/docker/metadata-action@v5
        with:
          images: hacklabkyiv/prismo-app

      - name: Login to GitHub Container Registry
        uses: https://github.com/docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: https://github.com/docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push
        uses: https://github.com/docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
